site_name: pytest-embedded

theme:
  name: "readthedocs"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  # admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # highlight:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # tabbed
  - pymdownx.tabbed:
      alternate_style: true
  # abbreviations
  - abbr
  - pymdownx.snippets

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            members_order: 'source'
            show_root_heading: True
      watch:
        - pytest-embedded
        - pytest-embedded-arduino
        - pytest-embedded-idf
        - pytest-embedded-jtag
        - pytest-embedded-qemu
        - pytest-embedded-serial
        - pytest-embedded-serial-esp

nav:
  - pytest-embedded: index.md
  - key_concepts.md
  - services.md
  - expecting.md
  - CONTRIBUTING.md
  - CHANGELOG.md
  - References:
    - references/pytest_embedded.md
    - references/pytest_embedded_serial.md
    - references/pytest_embedded_serial_esp.md
    - references/pytest_embedded_jtag.md
    - references/pytest_embedded_idf.md
    - references/pytest_embedded_arduino.md
    - references/pytest_embedded_qemu.md
