name: Test Python Packages

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [ main ]

jobs:
  test-python:
    timeout-minutes: 30
    runs-on:
      - self-hosted
      - multiboard
    strategy:
      matrix:
        python-version: ['3.7', '3.11']
      fail-fast: false
    container:
      image: python:${{ matrix.python-version }}-bullseye
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update && apt install -y socat
          pip install -U pip
          export PIP_EXTRA_INDEX_URL="https://dl.espressif.com/pypi"
          pip install cryptography --only-binary :all:
          pip install -r requirements.txt
          bash foreach.sh install
      - name: Check ports
        run: ls -la /dev/ttyUSB*
      - name: Run Tests with coverage
        run: |
          pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing \
            --cov=pytest-embedded/pytest_embedded/ \
            --cov=pytest-embedded-arduino/pytest_embedded_arduino/ \
            --cov=pytest-embedded-idf/pytest_embedded_idf/ \
            --cov=pytest-embedded-jtag/pytest_embedded_jtag/ \
            --cov=pytest-embedded-qemu/pytest_embedded_qemu/ \
            --cov=pytest-embedded-serial/pytest_embedded_serial/ \
            --cov=pytest-embedded-serial-esp/pytest_embedded_serial_esp/
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test_logs
          path: /tmp/pytest-embedded/
