name: Test Build Docs

on:
  pull_request:
    paths:
      - '**.py'
      - 'docs/**'
      - '*.md'

jobs:
  test-build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          bash foreach.sh install
          pip install -r docs/requirements.txt
      - name: Test build docs
        run: |
          cd docs && make html SPHINXOPTS="-W"
